import Quest1 from './Ques1.jsx'
import Quest2 from './Ques2.jsx'
import Quest3 from './Ques3.jsx'
import Quest4 from './Ques4.jsx'
import Quest5 from './Ques5.jsx'
import Quest6 from './Ques6.jsx'
import Quest7 from './Ques7.jsx'
import Quest8 from './Ques8.jsx'
import Quest9 from './Ques9.jsx'
import Quest10 from './Ques10.jsx'
import Quest11 from './Ques11.jsx'
import Quest12 from './Ques12.jsx'
import Quest13 from './Ques13.jsx'

export {Quest1, Quest2, Quest3, Quest4, Quest5, Quest6, Quest7, Quest8, Quest9, Quest10, Quest11, Quest12, Quest13}